export const siteData = {
  name: '朱幕座',
  romanizedName: 'Shumakuza',
  tagline: '幕が上がるたび、日本の物語が息づく。',
  description: '朱幕座は、歌舞伎、舞踊、和楽器、古典演目の魅力を初めての方にもわかりやすく案内する、架空の伝統芸能ガイドサイトです。',
  theaterName: '朱幕座 伝統芸能案内所',
  address: '東京都中央区日本橋人形町2-14-5 朱幕座ビル 2階',
  email: 'hello@shumakuza.jp',
  businessHours: '10:00〜18:00（月曜休み）',
  instagram: 'https://instagram.com/shumakuza.jp',

  disclaimer: '掲載している演目、劇場情報、開催情報、文化解説は架空または編集上の情報を含みます。実際の観劇や参加を検討する際は、各劇場・主催者・公式情報をご確認ください。',

  navigation: [
    { label: '私たちについて', href: '/about' },
    { label: '演目案内', href: '/performances' },
    { label: 'はじめての歌舞伎', href: '/beginner-guide' },
    { label: '劇場の楽しみ方', href: '/theater-experience' },
    { label: 'お問い合わせ', href: '/contact' },
  ],

  footerLinks: [
    { label: '私たちについて', href: '/about' },
    { label: '演目案内', href: '/performances' },
    { label: 'はじめての歌舞伎', href: '/beginner-guide' },
    { label: '劇場の楽しみ方', href: '/theater-experience' },
    { label: 'お問い合わせ', href: '/contact' },
    { label: 'プライバシーポリシー', href: '/privacy-policy' },
    { label: '利用規約', href: '/terms-and-conditions' },
  ],

  performances: [
    {
      id: 'kanjincho',
      title: '勧進帳に学ぶ義と情',
      category: '歌舞伎十八番',
      mood: '勇壮・感動',
      duration: '約60分',
      beginnerFriendly: true,
      visualHighlight: '武蔵坊弁慶の豪快な飛び六方',
      culturalPoint: '主君を守るため、偽りの勧進帳を読み上げる緊迫の場面。義理と人情の葛藤が描かれます。',
      description: '源義経一行が安宅の関を越えようとする物語。関守・富樫左衛門と弁慶の知略と情を交えた心理戦が見どころです。',
    },
    {
      id: 'sukeroku',
      title: '助六の華やかな江戸の世界',
      category: '歌舞伎十八番',
      mood: '華麗・痛快',
      duration: '約90分',
      beginnerFriendly: true,
      visualHighlight: '江戸一の伊達男、助六の登場',
      culturalPoint: '吉原を舞台にした色彩豊かな演目。粋な言葉、鮮やかな衣裳、テンポの良い掛け合いを楽しめます。',
      description: '紫の鉢巻と黒の着物が印象的な助六が、華やかな廓を歩く名作。江戸っ子の気風の良さが舞台いっぱいに広がります。',
    },
    {
      id: 'musumedojoji',
      title: '娘道成寺の舞の美しさ',
      category: '舞踊',
      mood: '優美・情念',
      duration: '約45分',
      beginnerFriendly: true,
      visualHighlight: '次々と変わる豪華な衣裳と舞',
      culturalPoint: '手ぬぐい、笠、鞨鼓などの小道具を用いながら、女方の技と情念が重なっていく大曲です。',
      description: '白拍子花子が道成寺を訪れ、さまざまな踊りを披露する舞踊の名作。引き抜きによる衣裳の変化も見逃せません。',
    },
    {
      id: 'renjishi',
      title: '連獅子に見る親子の力',
      category: '舞踊',
      mood: '力強い・厳か',
      duration: '約40分',
      beginnerFriendly: true,
      visualHighlight: '紅白の長い毛を振る勇壮な毛振り',
      culturalPoint: '親獅子が子を谷底へ落とし、這い上がった子だけを育てるという故事をもとにした迫力ある舞踊です。',
      description: '前半は親子の修行、後半は獅子の精となって現れる壮麗な構成。終盤の毛振りはまさに舞台のクライマックスです。',
    },
    {
      id: 'yoshitsune',
      title: '義経千本桜の物語',
      category: '時代物',
      mood: '悲哀・壮大',
      duration: '約120分',
      beginnerFriendly: false,
      visualHighlight: '狐忠信の軽快な動きと宙乗り',
      culturalPoint: '源平合戦の後日譚。親子の情愛、忠義、運命が交錯する三大名作のひとつです。',
      description: '源義経をめぐる人々の数奇な運命を描く壮大なドラマ。狐忠信の場面は初めての観劇にも印象深く残ります。',
    },
    {
      id: 'wagakki',
      title: '和楽器で味わう舞台の音',
      category: '音楽・解説',
      mood: '風流・雅',
      duration: '約30分',
      beginnerFriendly: true,
      visualHighlight: '三味線、太鼓、笛の生演奏',
      culturalPoint: '雨、風、雪、人物の心理まで表現する下座音楽の役割を、実演とともに体験できます。',
      description: '舞台を支える和楽器の奥深い世界を、初心者にもわかりやすく紹介する特別プログラムです。',
    },
  ],

  beginnerGuide: [
    {
      title: '歌舞伎とは',
      explanation: '江戸時代から約400年続く日本の伝統的な演劇です。音楽、舞踊、演技が一体となった総合芸術で、華やかな衣裳や舞台装置が特徴です。',
      beginnerTip: '物語のすべてを理解しようとしなくても大丈夫。まずは衣裳、音、動きの迫力を楽しむところから始めましょう。',
      commonMisunderstanding: '特別な知識がないと楽しめないわけではありません。イヤホンガイドや筋書を使えば、流れを追いやすくなります。',
      culturalNote: '「傾く」という、常識から少し外れた派手な美意識が語源とされています。',
    },
    {
      title: '見得とは',
      explanation: '感情が高まった場面で、役者がポーズを決めて静止する表現です。映画でいうクローズアップのように、重要な瞬間を強く印象づけます。',
      beginnerTip: '役者が止まったら、そこが注目ポイント。客席の空気まで一緒に変わります。',
      commonMisunderstanding: 'ただ止まるだけではなく、全身の筋肉、視線、呼吸を使う高度な演技です。',
      culturalNote: '見得が決まると、客席から屋号の掛け声がかかることがあります。',
    },
    {
      title: '隈取の意味',
      explanation: '役柄の性格や感情を表す独特の化粧法です。赤は勇気や正義、青は冷酷さや悪を表すなど、色にも意味があります。',
      beginnerTip: '顔の色を見るだけでも、その人物の立場や力強さを感じ取れます。',
      commonMisunderstanding: 'すべての役が隈取をするわけではありません。荒事の登場人物に多く見られます。',
      culturalNote: '顔の血管や筋肉を誇張して描くことで、怒りや生命力を表現したといわれます。',
    },
    {
      title: '花道の楽しみ方',
      explanation: '客席を貫いて舞台へ続く通路です。登場や退場だけでなく、重要な演技が行われる舞台の一部でもあります。',
      beginnerTip: '花道近くの席では、役者の息づかいまで感じられることがあります。',
      commonMisunderstanding: '単なる通路ではありません。本舞台と同時に芝居が進むこともあります。',
      culturalNote: '花道にある「すっぽん」からは、妖怪や幽霊などが登場することがあります。',
    },
    {
      title: '音楽と掛け声',
      explanation: '三味線、太鼓、笛などの音が、場面転換や人物の感情を支えます。客席からの掛け声も舞台の空気をつくる大切な要素です。',
      beginnerTip: '最初は音の変化に耳を傾けてみましょう。場面の緊張や笑いの合図が見えてきます。',
      commonMisunderstanding: '掛け声は誰でも自由にかけるものではなく、間合いを熟知した人が行うのが一般的です。',
      culturalNote: '拍子木の音は、幕の開閉や芝居の転換を知らせる合図です。',
    },
    {
      title: '初めて観るときの流れ',
      explanation: '少し早めに劇場へ行き、筋書やお弁当を選び、客席で開演を待ちます。幕間の時間も観劇体験の一部です。',
      beginnerTip: '一日中観る必要はありません。一幕だけ観られる席が用意されている劇場もあります。',
      commonMisunderstanding: '服装に厳しい決まりはありません。少しおしゃれをすると特別な気分が高まります。',
      culturalNote: '日常から離れた空間で過ごす時間そのものが、観劇の醍醐味です。',
    },
  ],

  theaterExperience: [
    {
      title: '開演前の過ごし方',
      content: '劇場には少し早めに到着し、非日常の空間を味わうのがおすすめです。売店で筋書やお土産を見ながら、幕が上がる前の高揚感を楽しみましょう。',
    },
    {
      title: '座席からの見え方',
      content: '1階席は役者の気配を近くで感じられ、2階席や3階席は舞台全体の構図や照明を見渡しやすい席です。好みに合わせて選べます。',
    },
    {
      title: '幕間の楽しみ',
      content: '演目と演目の間には幕間と呼ばれる休憩があります。お弁当や和菓子を味わいながら、次の場面を待つ時間も劇場ならではです。',
    },
    {
      title: '筋書の読み方',
      content: '筋書にはあらすじ、配役、衣裳、小道具、見どころがまとまっています。開演前や幕間に読むと、舞台の理解が深まります。',
    },
    {
      title: '終演後の余韻',
      content: '拍手が落ち着いたあとも、劇場の灯りやロビーの空気には物語の余韻が残ります。帰り道まで舞台の一部として楽しんでください。',
    },
  ],

  faqs: [
    {
      question: 'チケットはどこで購入できますか？',
      answer: '当サイトは架空の案内所のため、実際の販売は行っていません。各劇場や主催者の公式サイトをご確認ください。',
    },
    {
      question: 'どんな服装で行けばいいですか？',
      answer: '特別な決まりはありません。普段着でも問題ありませんが、少しおしゃれをすると観劇の気分が高まります。',
    },
    {
      question: '言葉が難しくて理解できるか不安です。',
      answer: 'イヤホンガイドや筋書を利用すると、あらすじや見どころを追いやすくなります。',
    },
    {
      question: '上演時間はどれくらいですか？',
      answer: '演目によって異なります。短いものは30分ほど、長い公演では幕間を含めて数時間になることもあります。',
    },
  ],
};
